JobPost/urls.py
from django.contrib import admin
from django.urls import path, include
from Jobs.views import HomeView, LandPageView






urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('Users.urls'),namespace='Users')),
    path('home/', HomeView.as_view(),name='home'),
    path('landpage/', LandPageView.as_view(),name='landpage'),  
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('jobs/',include(('Jobs.urls'), namespace='Jobs')),
    
    
    
]

Jobs/urls.py
from Jobs.api import ApplicantsViewset, ApplicationsViewset,ErDeclineApplicationViewset, ErAcceptApplicationViewset, JobDetailsViewset, JobListViewSet, PostJobViewSet, SearchViewset, EditJobViewset, ApplyJobViewset, PostedJobsViewset
from Jobs.api import EeAcceptJobViewset,EeDeclineJobViewset
from Jobs.views import ApplyJobView, EmployeeApplicationView, PostJobView, JobListView, ApplyJobView,EditJobView, PostedJobsView, ViewApplicantsView,JobDetailsView,NoAccessView
from django.urls import path


app_name = 'Jobs'

urlpatterns = [   
    path('post_job',PostJobViewSet.as_view({'post': 'post_job'})),
    path('api/job_post/',PostJobView.as_view(), name='job_post'),
    path('api/job_list',JobListViewSet.as_view({'get':'job_list'})),
    path('job_list', JobListView.as_view(),name='job_list'),
    path('api/job_search',SearchViewset.as_view({'get':'job_search'})),
    path('apply_job/<int:pk>',ApplyJobView.as_view(),name='apply_job'),
    path('api/apply_job/<int:pk>',ApplyJobViewset.as_view({'post':'apply'})),
    path('edit_job/<int:pk>',EditJobView.as_view(),name='edit_job'),
    path('api/edit_job/<int:pk>',EditJobViewset.as_view({'post': 'job_edit'})),
    path('view_applicants/<int:pk>', ViewApplicantsView.as_view(), name='view_applicants'),
    path('api/view_applicants/<int:pk>',ApplicantsViewset.as_view({'get':'applicant_list'})),
    path('posted_jobs/<int:pk>',PostedJobsView.as_view(), name='posted_jobs'),
    path('api/posted_jobs/<int:pk>',PostedJobsViewset.as_view({'get':'job_list'})),
    path('api/employer_accept/<int:pk>',ErAcceptApplicationViewset.as_view({'post':'accept'}), name='api_employer_accept'),
    path('api/employer_decline/<int:pk>',ErDeclineApplicationViewset.as_view({'post':'decline'})),
    path('view_applications/<int:pk>',EmployeeApplicationView.as_view(),name='view_applications'),
    path('api/view_applications/<int:pk>',ApplicationsViewset.as_view({'get':'application_list'})),
    path('api/employee_accept/<int:pk>',EeAcceptJobViewset.as_view({'post':'accept'})),
    path('api/employee_decline/<int:pk>',EeDeclineJobViewset.as_view({'post':'decline'})),
    path('api/job_details/<int:pk>',JobDetailsViewset.as_view({'get':'job_details'})),
    path('job_details/<int:pk>', JobDetailsView.as_view(),name='job_details'),
    path('no_access',NoAccessView.as_view(),name='no_access'),
   

    # path('api-token-auth/', CustomAuthToken.as_view(), name='login'),   
]

Users/urls.py
from Users.api import LogoutViewset, SignupViewset, LoginViewset,EditProfileViewset
from Users.views import EditProfileView, LoginView, SignupView
from django.urls import path
from django.urls import include, path
from rest_framework import routers
from rest_framework.authtoken import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'Users'

urlpatterns = [   
    path('login/', LoginViewset.as_view({'post': 'login'})), 
    path('api/login/', LoginView.as_view(), name='login'),
    path('api/signup/',SignupView.as_view(), name='signup'),
    path('signup/',SignupViewset.as_view({'post': 'signup'})),
    path('logout/',LogoutViewset.as_view({'get':'logout'}), name='logout'),
    path('edit_profile/<int:pk>',EditProfileView.as_view(), name='edit_profile'),
    path('api/edit_profile/<int:pk>',EditProfileViewset.as_view({'post':'edit_profile'})),
    # path('api-token-auth/', CustomAuthToken.as_view(), name='login'),
    
]

templates/base.html
{% load rest_framework %}
{% load static %}
{% include 'navbar.html ' %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<html>  
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    

  </head>
<body>
  <div class="container mt-4">
      
  
    {% block content %}


    
    {% endblock %}
  </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    {% block extra_js %}

    {% endblock %}
  
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{%load static %}
{% block content %}
<input type ="hidden" id="user" value="{{user.pk}}">
<input type ="hidden" id="status" value="{{user.is_employer}}">
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-2">           
                {% csrf_token %}
                <input id="sj" class="form-control me-2" type ="search" aria-label="Search" name="sj" value ="{{request.GET.get.sj}}" placeholder="Enter A job title">
        </div>
        <div class="col-sm">
                <input id="jl" class="form-control me-2" type ="search" aria-label="Search" name="jl" value ="{{request.GET.get.jl}}" placeholder="Enter Location">             
        </div>
        <div class="col-sm">
            <select id="cat" class="form-control me-2"  name="cat" >
                <option value=""selected>Job Category</option>
                <option value="Computer">Computer</option>
                <option value="Finance">Finance </option>
                <option value="Entertainment">Entertainment</option>  
            </select>             
        </div>
        <div class="col-sm">
            <select class="form-control" id="sal_range" placeholder="Salary Range" name="sal_range">
                <option value=""selected>Minimum Salary Offer</option>
                <option value="10000">10000</option>
                <option value="12000">12000</option>           
                <option value="50000">50000 </option>
                <option value="100000">100000</option>           
            </select>
        </div>
         <div class="col-sm-2">
            <button id="search_btn" class="btn btn-success">Search</button>
        </div>            
    </div>  
    <br>
    <div class="container">   
        <div id="failed_div"></div>   
        <div class= "row" id="div_body">                
        </div>         
    </div>
</div>

{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'dashboard.js' %}"></script>
{% endblock %}

templates/landpage.html
<h1>LandPage</h1>

templates/navbar.html
{%load static %}
{% load rest_framework %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
   
        {%if user.is_authenticated %}       
            <a class="navbar-brand" href="{% url 'home' %}">
                Find Jobs
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                
            {%if user.is_employee is False %}   
            <ul class="navbar-nav mr-auto">      
                <li class="nav-item">
                    <a id="view_posted_jobs_btn" class="nav-link" href="{%url 'Jobs:posted_jobs' user.pk %} ">
                        View Posted Jobs <span id="notification" class="badge badge-light">0</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'Jobs:job_post' %}">
                        Post a Job
                    </a>
                </li>
            </ul> 
            {%elif user.is_employer is False %}
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a id="view_jobs_applied_btn" class="nav-link" href="{% url 'Jobs:view_applications' user.pk%}">
                        View Jobs Applied to
                    </a>
                </li>
            </ul>
            {%else%}
            <ul class="nav navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'Jobs:job_post' %}">
                        Post a Job
                    </a>
                </li>            
                <li class="nav-item">
                    <a id="view_posted_jobs_btn" class="nav-link" href="{%url 'Jobs:posted_jobs' user.pk %} ">
                       View Posted Jobs  
                       <span id="notification" class="badge badge-light">0</span>
                        </span>
                    </a>
                    
                </li>
                <li class="nav-item">
                    <a id="view_jobs_applied_btn" class="nav-link" href="{% url 'Jobs:view_applications' user.pk%}">
                        View Jobs Applied to 
                    </a>
                </li>
            </ul>
            <button type="button" class="btn btn-primary">
              
            </button>
            {% endif %}
            <ul class="nav navbar-nav mt-2 mt-lg-0">
                <li class="nav-item">
                    <a id="edit_profile_btn" class="nav-link" href="{% url 'Users:edit_profile' user.pk %}">
                        Edit Profile
                    </a>  
                </li>  
                <li class="nav-item">                                 
                    <a class="nav-link" id ="logout_button"  href="{% url 'Users:logout' %}">
                        Logout
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" id="navbarDropdownMenuLink">
                        {%if user.is_employer is False %}                        
                            {% if user.is_employed is False %}
                            <p id="job_status_title">Unemployed</p>
                            {% else %}
                            <p id="job_status_title">Employed</p>                                       
                            {% endif %}                         
                        {% elif user.is_employer is True and user.is_employee is True %}
                            <p id="job_status_title">Admin</p>
                        {% elif user.is_employer is True %}
                            <p id="job_status_title">Employer</p>
                        {% endif %}
                    </a>   
                </li> 
            </ul>      
        </div>
        {% else %}    
        <ul class="nav navbar-nav">                               
            <li class="nav-item"></li>
                <a class="navbar-brand" href="{% url 'home' %}">
                    Find Jobs
                </a> 
            </li>           
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Users:login' %}">
                    Login
                </a> 
            </li>  
            <li class="nav-item"> 
                <a class="nav-link" href="{%url 'Users:signup' %}">
                    Signup
                </a>
            </li> 
        {% endif %}  

</nav>  

{% block extra_js %}
<script type="text/javascript" src="{% static 'dashboard.js' %}"></script>
{% endblock %}